import Head from 'next/head'
import React, {useState} from 'react';
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import commerce from '../lip/commerce'
import Header from '../components/Header';
import {IoHeartOutline, IoHeart} from 'react-icons/io5'
import {MdAddShoppingCart} from 'react-icons/md'
import Product from '../components/Product';
import Footer from '../components/Footer';
export default function Home({products}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400&display=swap" rel="stylesheet"></link>
      </Head>
      <Header/>
      <main className={styles.main}>
        <div style={{margin: '15rem 0', fontSize:'2rem'}}>
          <p>
          MOISTURE IS THE ESSENCE OF WETNESS, AND WETNESS IS THE ESSENCE OF BEAUTY.
          </p>
          <Link href="/">
          <a>
            Find out more →
          </a>
          </Link>
        </div>
        <div style={{backgroundColor: 'var(--color-secondary)', padding: '5rem'}}>
          <h2>Categories</h2>
          <section className={styles.categories}>
            <img src="3.jpeg"/>
            <img src="2.jpeg"/>
            <img src="1.jpeg"/>
            </section>
        </div>
        <div style={{display: 'flex', flexWrap: 'wrap', justifyContent: 'center', marginTop: '5rem'}}>
        <h2 style={{width: '100%'}}>Featured Products</h2>
          <section style={{width: '80%'}} className={styles.products}>
        
    {products.map((product)=> {
        return(
          <Product key={product.id} product={product}/>
        )
      })}
  
     
      </section>
      </div>
      </main>
<Footer/>
    </div>
  )
}

export const getStaticProps = async () => {
  const {data: products} = await commerce.products.list()

  return {
    props: {
      products,
    }
  }
}